def dict_init():
    para_dict = ({
        # Global initialization
        'input_dir' : "../inputs/sam_remain_class_img_val_19_3_0.01_split",
        'output_dir' : "./output/sam_remain_class_mask_val_19_3_test",
        'device' : "npu:0",

        'sam_first_sam_checkpoint' : "./SAM/sam_vit_h_4b8939.pth",
        'sam_first_model_type': "vit_h",
        'sam_first_points_per_side': 32,
        'sam_first_pred_iou_thresh': 0.9,
        'sam_first_stability_score_thresh': 0.9,
        'sam_first_crop_n_layers': 1,
        'sam_first_crop_nms_thresh': 0.7,
        'sam_first_crop_overlap_ratio': 512 / 1500,
        'sam_first_min_mask_region_area': 5000,
        'sam_first_output_mode': 'binary_mask',
        'sam_first_resize_max_side': 2480,

        'mask_combine_min_area_ratio': 0.002,
        'mask_combine_iou_filter_thresh': 0.9,
        'mask_combine_contain_thresh': 0.9,
        'mask_combine_erode_kernel_size': 7,
        'mask_combine_erode_erode_iter': 6,
        'mask_combine_erode_dilate_iter': 4,

        "sam_2nd_model_type": "vit_h",
        "sam_2nd_model_path": "./SAM/sam_vit_h_4b8939.pth",
        "sam_2nd_points_per_side": 32,
        "sam_2nd_pred_iou_thresh": 0.9,
        "sam_2nd_stability_score_thresh": 0.9,
        "sam_2nd_crop_n_layers": 1,
        "sam_2nd_crop_nms_thresh": 0.7,
        "sam_2nd_crop_overlap_ratio": 512 / 1500,
        "sam_2nd_min_mask_region_area": 500,
        "sam_2nd_output_mode": "binary_mask",
        "sam_2nd_padding_ratio": 0.1,
        "sam_2nd_kernel_ratio": 0.004,
        "sam_2nd_erode_iter": 4,
        "sam_2nd_dilate_iter": 4,
        "sam_2nd_min_area_ratio": 0.01,
        "sam_2nd_overlap_thresh": 0.9,

        'sam_remain_sam_checkpoint': "./sam_vit_h_4b8939.pth",
        'sam_remain_model_type': "vit_h",
        'sam_remain_points_per_side': 64,
        'sam_remain_pred_iou_thresh': 0.8,
        'sam_remain_stability_score_thresh': 0.7,
        'sam_remain_crop_n_layers': 2,
        'sam_remain_crop_nms_thresh': 0.7,
        'sam_remain_crop_overlap_ratio': 0.4,
        'sam_remain_min_mask_region_area': 1500,
        'sam_remain_output_mode': 'binary_mask',
        'sam_remain_resize_max_side': 2480,
        'sam_remain_iou_filter_thresh': 0.9,
        'sam_remain_iou_contain_thresh': 0.8,
        'sam_remain_erode_kernel_size_ratio': 0.004,
        'sam_remain_erode_erode_iter': 4,
        'sam_remain_erode_dilate_iter': 4,
        'sam_remain_min_area_ratio': 0.0004,
        'sam_remain_min_area_ratio_loop': 0.00015,


        'mask_split_mode': 'ccomp',
        'mask_split_save_fullsize_mask': True,
        'mask_split_chain':'simple',
        'mask_split_min_area': 0,
        'mask_split_keep_top_k': None,
        'mask_split_binary_dir' : None,
        'mask_split_show_progress': False,

        'mask_cut_padding_ratio': 0.1,
        'mask_cut_output_path': 0.1,

        'yolo_inference_weights_path': "./runs/detect/train/weights/best.pt",
        'yolo_inference_save_json': "./runs/result.json",
        'yolo_inference_save': True,
        'yolo_inference_save_txt': True,
        'yolo_inference_save_conf': True,
        'yolo_inference_project': "./runs/detect",
        'yolo_inference_name': "result",
        'yolo_inference_num_classes' : 19

    })
    return para_dict
